[package]
name = "url-compressor"
version = "0.1.3"
authors = ["yanorei32 <yanorei@hotmail.co.jp>"]
edition = "2024"
repository = "https://github.com/yanorei32/url-compressor"
license = "BSD-2-Clause"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.122"
base32768 = { git = "https://github.com/EEWBot/base32768-rs", version = "0.1.0" }
zstd = "0.13.3"

[profile.release]
opt-level = "s"
