name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  RUST_CACHE_VERSION: v1

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: Swatinem/rust-cache@v2.9.1
        with:
          prefix-key: ${{ env.RUST_CACHE_VERSION }}-rust

      - name: Build
        run: |
          cargo install wasm-pack
          wasm-pack build --target web
          tar cvhf static.tar.gz static/

      - name: pre-release
        uses: softprops/action-gh-release@v3.0.1
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: master-${{ github.sha }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            *.tar.gz

      - name: tagged-release
        uses: softprops/action-gh-release@v3.0.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            *.tar.gz
